# Generated by Django 3.0.7 on 2020-06-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_owner'),
        ('contacts', '0003_contact_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_contacts', to='jobs.Job'),
        ),
    ]
