# Generated by Django 3.0.7 on 2020-06-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200606_0930'),
        ('contacts', '0003_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_contacts', to='jobs.Job'),
        ),
    ]
