# Generated by Django 3.0.7 on 2020-06-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
