# Generated by Django 3.0.7 on 2020-06-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
