# Generated by Django 3.0.7 on 2020-06-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('task_categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_Category',
            new_name='TaskCategory',
        ),
    ]
