# Generated by Django 3.0.7 on 2020-06-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=1000)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_categories.Task_Category')),
            ],
        ),
    ]
