# Generated by Django 3.0.7 on 2020-06-05 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_owner'),
        ('tasks', '0002_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_task', to='jobs.Job'),
        ),
    ]
